name: 'forex_etl'
version: '1.0.0'
config-version: 2

profile: 'forex_pipeline'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  forex_etl:
    staging:
      +materialized: view
      +schema: staging
    core:
      +materialized: table
      +schema: core
    marts:
      +materialized: table
      +schema: marts
